[pytest]
norecursedirs = scripts/debug
testpaths = tests
asyncio_default_fixture_loop_scope = function
filterwarnings =
    ignore:urllib3 v2 only supports OpenSSL
    ignore:builtin type SwigPyPacked has no __module__ attribute:DeprecationWarning
    ignore:builtin type SwigPyObject has no __module__ attribute:DeprecationWarning
    ignore:builtin type swigvarlink has no __module__ attribute:DeprecationWarning
markers =
    serial: mark test to run in the main worker only (not parallelised)
