"""Tests that CI trigger seed data covers all STARTER action types.

The ``scripts/ci_trigger_data.py`` file is generated by
``scripts/export_trigger_embeddings.py --from-starter`` and must include
embeddings for every action_type defined in the canonical STARTER list
(``src/triggers/trigger_matcher.STARTER``).

If this test fails it means ``ci_trigger_data.py`` is stale and must be
regenerated:

    .venv/bin/python scripts/export_trigger_embeddings.py --from-starter --out scripts/ci_trigger_data.py
"""

import pytest

from src.triggers.trigger_matcher import STARTER
from scripts.ci_trigger_data import TRIGGERS


class TestCiTriggerDataCompleteness:
    """Ensure CI trigger data is in sync with STARTER."""

    def test_ci_trigger_count_matches_starter(self):
        """CI trigger data should have the same number of entries as STARTER."""
        assert len(TRIGGERS) == len(STARTER), (
            f"CI trigger data has {len(TRIGGERS)} entries but STARTER has "
            f"{len(STARTER)}. Regenerate with:\n"
            "  .venv/bin/python scripts/export_trigger_embeddings.py "
            "--from-starter --out scripts/ci_trigger_data.py"
        )

    def test_ci_trigger_action_types_cover_starter(self):
        """Every action_type in STARTER must be present in CI trigger data."""
        starter_actions = set(s.get("action_type") for s in STARTER)
        ci_actions = set(t.get("action_type") for t in TRIGGERS)
        missing = starter_actions - ci_actions
        assert not missing, (
            f"CI trigger data is missing action types: {sorted(missing)}. "
            f"Regenerate with:\n"
            "  .venv/bin/python scripts/export_trigger_embeddings.py "
            "--from-starter --out scripts/ci_trigger_data.py"
        )

    def test_confirm_yes_triggers_present(self):
        """confirm_yes triggers must be present for lesson confirmation flow."""
        confirm_yes = [t for t in TRIGGERS if t.get("action_type") == "confirm_yes"]
        assert len(confirm_yes) > 0, (
            "No confirm_yes triggers in CI data. The lesson confirmation flow "
            "(_semantic_yes_no) requires these triggers to classify 'yes' "
            "responses. Regenerate ci_trigger_data.py."
        )

    def test_confirm_no_triggers_present(self):
        """confirm_no triggers must be present for lesson confirmation flow."""
        confirm_no = [t for t in TRIGGERS if t.get("action_type") == "confirm_no"]
        assert len(confirm_no) > 0, (
            "No confirm_no triggers in CI data. The lesson confirmation flow "
            "(_semantic_yes_no) requires these triggers to classify 'no' "
            "responses. Regenerate ci_trigger_data.py."
        )

    def test_ci_trigger_embeddings_are_non_empty(self):
        """Every trigger in CI data should have a non-empty embedding vector."""
        for i, t in enumerate(TRIGGERS):
            emb = t.get("embedding", [])
            assert len(emb) > 0, (
                f"Trigger {i} ({t.get('name')}) has empty embedding. "
                "Regenerate ci_trigger_data.py."
            )


class TestSemanticYesNoWithRealTriggers:
    """Verify _semantic_yes_no works with real CI trigger embeddings.

    These tests force-refresh the TriggerMatcher singleton so it loads
    the freshly-seeded test DB triggers, then call _semantic_yes_no
    with real embeddings to confirm the lesson confirmation flow works.
    """

    @pytest.mark.asyncio
    async def test_semantic_yes_no_classifies_yes(self, db_session):
        """'yes' should be classified as (True, False) by _semantic_yes_no."""
        from src.triggers.trigger_matcher import refresh_trigger_matcher_cache
        from src.services.dialogue.reminder_handler import _semantic_yes_no

        # Force the singleton to reload from the test DB (which has 123 triggers)
        refresh_trigger_matcher_cache()

        is_yes, is_no = await _semantic_yes_no("yes", None)
        assert is_yes is True, f"Expected 'yes' -> (True, _), got ({is_yes}, {is_no})"
        assert is_no is False, f"Expected 'yes' -> (_, False), got ({is_yes}, {is_no})"

    @pytest.mark.asyncio
    async def test_semantic_yes_no_classifies_no(self, db_session):
        """'no' should be classified as (False, True) by _semantic_yes_no."""
        from src.triggers.trigger_matcher import refresh_trigger_matcher_cache
        from src.services.dialogue.reminder_handler import _semantic_yes_no

        refresh_trigger_matcher_cache()

        is_yes, is_no = await _semantic_yes_no("no", None)
        assert is_yes is False, f"Expected 'no' -> (False, _), got ({is_yes}, {is_no})"
        assert is_no is True, f"Expected 'no' -> (_, True), got ({is_yes}, {is_no})"

    @pytest.mark.asyncio
    async def test_semantic_yes_no_classifies_ja(self, db_session):
        """Norwegian 'ja' should be classified as yes."""
        from src.triggers.trigger_matcher import refresh_trigger_matcher_cache
        from src.services.dialogue.reminder_handler import _semantic_yes_no

        refresh_trigger_matcher_cache()

        is_yes, is_no = await _semantic_yes_no("ja ferdig", None)
        assert is_yes is True, f"Expected 'ja ferdig' -> (True, _), got ({is_yes}, {is_no})"
        assert is_no is False

    @pytest.mark.asyncio
    async def test_semantic_yes_no_classifies_nei(self, db_session):
        """Norwegian 'nei' should be classified as no."""
        from src.triggers.trigger_matcher import refresh_trigger_matcher_cache
        from src.services.dialogue.reminder_handler import _semantic_yes_no

        refresh_trigger_matcher_cache()

        is_yes, is_no = await _semantic_yes_no("nei ikke ferdig", None)
        assert is_yes is False, f"Expected 'nei ikke ferdig' -> (False, _), got ({is_yes}, {is_no})"
        assert is_no is True
