"""add is_active to memory

Revision ID: 579b16a573a2
Revises: de6254f61b96
Create Date: 2026-02-02 11:42:42.127781

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "579b16a573a2"
down_revision: Union[str, Sequence[str], None] = "de6254f61b96"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("memories", sa.Column("is_active", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("memories", "is_active")
    # ### end Alembic commands ###
