"""add user timezone column

Revision ID: a3f4b2c1d6e7
Revises: 579b16a573a2
Create Date: 2026-02-06 12:50:00.000000

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3f4b2c1d6e7"
down_revision: Union[str, Sequence[str], None] = "579b16a573a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("timezone", sa.String(length=64), nullable=True, server_default=sa.text("'UTC'")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "timezone")
    # ### end Alembic commands ###
