"""Initial schema

Revision ID: de6254f61b96
Revises: 
Create Date: 2026-02-02 10:31:33.215531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'de6254f61b96'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('difficulty_level', sa.String(length=32), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('lesson_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('opted_in', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('memories',
    sa.Column('memory_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ttl_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('memory_id')
    )
    op.create_table('message_logs',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('external_message_id', sa.String(length=128), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('schedules',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('schedule_type', sa.String(length=32), nullable=False),
    sa.Column('cron_expression', sa.String(length=64), nullable=False),
    sa.Column('next_send_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.lesson_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_table('unsubscribes',
    sa.Column('unsubscribe_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('compliance_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('unsubscribe_id')
    )
    bind = op.get_bind()
    inspector = inspect(bind)
    if 'memory' in inspector.get_table_names():
        existing_indexes = {idx.get('name') for idx in inspector.get_indexes('memory')}
        for index_name in [
            op.f('ix_memory_key'),
            op.f('ix_memory_memory_id'),
            op.f('ix_memory_user_id'),
            op.f('ix_memory_value_hash'),
        ]:
            if index_name in existing_indexes:
                op.drop_index(index_name, table_name='memory')
        op.drop_table('memory')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory',
    sa.Column('memory_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('key', sa.VARCHAR(length=100), nullable=False),
    sa.Column('value', sa.TEXT(), nullable=False),
    sa.Column('value_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('confidence', sa.INTEGER(), nullable=True),
    sa.Column('source', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('conflict_group_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('archived_at', sa.DATETIME(), nullable=True),
    sa.Column('ttl_expires_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('memory_id')
    )
    op.create_index(op.f('ix_memory_value_hash'), 'memory', ['value_hash'], unique=False)
    op.create_index(op.f('ix_memory_user_id'), 'memory', ['user_id'], unique=False)
    op.create_index(op.f('ix_memory_memory_id'), 'memory', ['memory_id'], unique=False)
    op.create_index(op.f('ix_memory_key'), 'memory', ['key'], unique=False)
    op.drop_table('unsubscribes')
    op.drop_table('schedules')
    op.drop_table('message_logs')
    op.drop_table('memories')
    op.drop_table('users')
    op.drop_table('lessons')
    # ### end Alembic commands ###
