"""Export trigger_embeddings from the DB into a precomputed Python data file.

Usage:
  python scripts/export_trigger_embeddings.py --out scripts/ci_trigger_data.py

This reads the `trigger_embeddings` table and writes a pure-Python file
containing a `TRIGGERS` list where each embedding is serialized as a list
of floats. The resulting file can be checked into the repo and used by CI
to seed the database deterministically without heavy ML dependencies.

Safety: by default this script refuses to run when it detects it would
operate on the `prod.db` unless `ALLOW_EXPORT_PROD=true` is set in env.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
import os

# Ensure repo root importable
REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import json
import numpy as np
from src.models.database import SessionLocal, TriggerEmbedding


def is_prod_db_url() -> bool:
    from src.config import settings
    url = getattr(settings, 'DATABASE_URL', '')
    return 'prod.db' in (url or '')


def export(out_path: Path) -> int:
    if is_prod_db_url() and os.environ.get('ALLOW_EXPORT_PROD', '').lower() not in ('1', 'true', 'yes'):
        print('Refusing to export from prod DB unless ALLOW_EXPORT_PROD=1 is set in env')
        return 2

    db = SessionLocal()
    try:
        rows = db.query(TriggerEmbedding).all()
        triggers = []
        for r in rows:
            try:
                arr = np.frombuffer(r.embedding, dtype=np.float32)
                emb = arr.tolist()
            except Exception:
                emb = []
            triggers.append({
                'name': r.name,
                'action_type': r.action_type,
                'threshold': float(r.threshold or 0.75),
                'embedding': emb,
            })

        # Write a Python module for CI consumption
        out_text = """
# Autogenerated by scripts/export_trigger_embeddings.py
TRIGGERS = \
""" + json.dumps(triggers, indent=2) + "\n"

        out_path.write_text(out_text, encoding='utf8')
        print(f'Wrote {len(triggers)} triggers to {out_path}')
        return 0
    finally:
        db.close()


def export_from_starter(out_path: Path, model_name: str | None = None) -> int:
    """Export embeddings computed from the STARTER utterances using the local model.

    This avoids touching the DB and directly computes model embeddings for each
    starter utterance, writing the same `TRIGGERS` format as the DB exporter.
    """
    # Safety: do not run against prod concerns (we only read STARTER, but keep guard)
    if is_prod_db_url() and os.environ.get('ALLOW_EXPORT_PROD', '').lower() not in ('1', 'true', 'yes'):
        print('Refusing to run exporter in prod context; set ALLOW_EXPORT_PROD=1 to override')
        return 2

    try:
        from src.triggers.trigger_matcher import STARTER
        from src.services.embedding_service import get_embedding_service
    except Exception as e:
        print('Failed to import STARTER or embedding service:', e)
        return 3

    # Ensure we use local backend for computed embeddings
    svc = get_embedding_service()
    if model_name:
        os.environ.setdefault('SENTENCE_TRANSFORMERS_MODEL', model_name)

    # Warn if local backend isn't configured; user can set EMBEDDING_BACKEND env
    if getattr(svc, 'backend', None) != 'local':
        print('Warning: embedding service backend is not "local". For reliable local export set EMBEDDING_BACKEND=local')

    texts = [s['utterance'] for s in STARTER]
    print(f'Computing embeddings for {len(texts)} starter utterances using local model...')
    try:
        embs = svc.batch_embed(texts)
        # batch_embed may be coroutine or return awaitable; handle if needed
        import asyncio
        if asyncio.iscoroutine(embs):
            embs = asyncio.run(embs)
    except Exception as e:
        print('Embedding computation failed:', e)
        return 4

    triggers = []
    for spec, emb in zip(STARTER, embs):
        if emb is None:
            print('Failed to compute embedding for:', spec.get('utterance'))
            return 5
        triggers.append({
            'name': spec.get('name') or spec.get('utterance'),
            'action_type': spec.get('action_type'),
            'threshold': float(spec.get('threshold', 0.75)),
            'embedding': list(map(float, emb)),
        })

    out_text = """
# Autogenerated by scripts/export_trigger_embeddings.py (--from-starter)
TRIGGERS = \
""" + json.dumps(triggers, indent=2) + "\n"

    out_path.write_text(out_text, encoding='utf8')
    print(f'Wrote {len(triggers)} starter triggers to {out_path}')
    return 0


def main(argv=None):
    p = argparse.ArgumentParser()
    p.add_argument('--out', default='scripts/ci_trigger_data.py')
    group = p.add_mutually_exclusive_group()
    group.add_argument('--from-starter', action='store_true', help='Compute embeddings from STARTER using local model and write TRIGGERS')
    group.add_argument('--from-db', action='store_true', help='Export trigger_embeddings rows from DB into TRIGGERS module')
    p.add_argument('--model', help='Optional sentence-transformers model name to use when --from-starter')
    args = p.parse_args(argv)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)

    # Default behavior: prefer computing from starter utterances
    if args.from_db:
        return export(out)
    # from-starter explicitly set, or default
    model_name = args.model or None
    return export_from_starter(out, model_name=model_name)


if __name__ == '__main__':
    raise SystemExit(main())
