"""Export trigger_embeddings from the DB into a precomputed Python data file.

Usage:
  python scripts/export_trigger_embeddings.py --out scripts/ci_trigger_data.py

This reads the `trigger_embeddings` table and writes a pure-Python file
containing a `TRIGGERS` list where each embedding is serialized as a list
of floats. The resulting file can be checked into the repo and used by CI
to seed the database deterministically without heavy ML dependencies.

Safety: by default this script refuses to run when it detects it would
operate on the `prod.db` unless `ALLOW_EXPORT_PROD=true` is set in env.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
import os

# Ensure repo root importable
REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import json
import numpy as np
from src.models.database import SessionLocal, TriggerEmbedding


def is_prod_db_url() -> bool:
    from src.config import settings
    url = getattr(settings, 'DATABASE_URL', '')
    return 'prod.db' in (url or '')


def export(out_path: Path) -> int:
    if is_prod_db_url() and os.environ.get('ALLOW_EXPORT_PROD', '').lower() not in ('1', 'true', 'yes'):
        print('Refusing to export from prod DB unless ALLOW_EXPORT_PROD=1 is set in env')
        return 2

    db = SessionLocal()
    try:
        rows = db.query(TriggerEmbedding).all()
        triggers = []
        for r in rows:
            try:
                arr = np.frombuffer(r.embedding, dtype=np.float32)
                emb = arr.tolist()
            except Exception:
                emb = []
            triggers.append({
                'name': r.name,
                'action_type': r.action_type,
                'threshold': float(r.threshold or 0.75),
                'embedding': emb,
            })

        # Write a Python module for CI consumption
        out_text = """
# Autogenerated by scripts/export_trigger_embeddings.py
TRIGGERS = \
""" + json.dumps(triggers, indent=2) + "\n"

        out_path.write_text(out_text, encoding='utf8')
        print(f'Wrote {len(triggers)} triggers to {out_path}')
        return 0
    finally:
        db.close()


def main(argv=None):
    p = argparse.ArgumentParser()
    p.add_argument('--out', default='scripts/ci_trigger_data.py')
    args = p.parse_args(argv)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    return export(out)


if __name__ == '__main__':
    raise SystemExit(main())
